# Generated by Django 5.2.9 on 2025-12-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_last_login_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Общедоступен'),
        ),
    ]
