# Generated by Django 5.2.9 on 2025-12-04 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('core', '0004_user_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(null=True, verbose_name='Описание цели')),
                ('target_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Целевой показатель')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('is_public', models.BooleanField(default=True, verbose_name='Общедоступно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.user')),
            ],
            options={
                'db_table': 'goals',
            },
        ),
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('progress_date', models.DateField(verbose_name='Текущая дата')),
                ('current_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Текущий показатель')),
                ('notes', models.TextField(null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_progresses', to='goals.goal')),
            ],
            options={
                'db_table': 'goal_progresses',
            },
        ),
    ]
