# Generated by Django 5.2.9 on 2025-12-04 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('core', '0004_user_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(null=True, verbose_name='Описание цели')),
                ('frequency_type', models.IntegerField(verbose_name='Длина временного промежутка')),
                ('frequency_value', models.IntegerField(verbose_name='Частота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Выполняется')),
                ('is_public', models.BooleanField(default=True, verbose_name='Общедоступно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='core.user')),
            ],
            options={
                'db_table': 'habits',
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('log_date', models.DateField(verbose_name='Текущая дата')),
                ('status', models.CharField(choices=[('completed', 'Выполнено'), ('skipped', 'Пропущено'), ('failed', 'Провалено')], default='completed', max_length=20, verbose_name='Роль')),
                ('notes', models.TextField(null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to='habits.habit')),
            ],
            options={
                'db_table': 'habit_logs',
            },
        ),
    ]
