# Generated by Django 5.2.9 on 2025-12-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency_type',
            field=models.PositiveIntegerField(verbose_name='Длина временного промежутка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency_value',
            field=models.PositiveIntegerField(verbose_name='Частота'),
        ),
    ]
