# Generated by Django 5.2.9 on 2025-12-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_create_audit_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
