# Generated by Django 5.2.9 on 2025-12-16 20:13

import audit.models
import django.contrib.postgres.fields
import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_id'),
        ('core', '0004_user_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100)),
                ('total_processed', models.PositiveIntegerField(default=0)),
                ('successful', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None)),
                ('updated_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None)),
                ('batches_processed', models.PositiveIntegerField(default=0)),
                ('batch_size', models.PositiveIntegerField(default=100)),
                ('created_at', audit.models.NowDefaultField()),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_logs', to='core.user')),
            ],
            options={
                'db_table': 'batch_logs',
            },
        ),
    ]
