# Generated by Django 5.2.9 on 2025-12-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_batchlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchlog',
            name='updated_ids',
        ),
    ]
