# Generated by Django 5.2.9 on 2025-12-04 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_user_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Подписан')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_made', to='core.user')),
                ('subscribing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_received', to='core.user')),
            ],
            options={
                'db_table': 'subscriptions',
                'unique_together': {('subscriber', 'subscribing')},
            },
        ),
    ]
