# Generated by Django 5.2.9 on 2025-12-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pk',
            field=models.CompositePrimaryKey('subscriber', 'subscribing', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='id',
        ),
    ]
