# Generated by Django 5.2.9 on 2025-12-05 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('target_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Целевой показатель')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата начала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'db_table': 'challenges',
            },
        ),
        migrations.CreateModel(
            name='ChallengeCategory',
            fields=[
                ('pk', models.CompositePrimaryKey('challenge', 'category', blank=True, editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_categories', to='categories.category')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_categories', to='challenges.challenge')),
            ],
            options={
                'db_table': 'challenge_categories',
            },
        ),
        migrations.CreateModel(
            name='GoalChallenge',
            fields=[
                ('pk', models.CompositePrimaryKey('goal', 'challenge', blank=True, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_challenges', to='challenges.challenge')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_challenges', to='goals.goal')),
            ],
            options={
                'db_table': 'goal_challenges',
            },
        ),
    ]
