# Generated by Django 5.2.9 on 2025-12-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_create_sql_functions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='target_value',
        ),
    ]
