DROP FUNCTION IF EXISTS calculate_habit_consistency(habit_id_param BIGINT);
DROP FUNCTION IF EXISTS calculate_goal_completion_percentage(p_goal_id BIGINT);
DROP VIEW IF EXISTS user_progress_analytics;
DROP FUNCTION IF EXISTS count_challenge_participants(challenge_id_param BIGINT);
DROP FUNCTION IF EXISTS count_challenge_goals(challenge_id_param BIGINT);
DROP FUNCTION IF EXISTS avg_challenge_progress(challenge_id_param BIGINT);
DROP FUNCTION IF EXISTS is_challenge_active(challenge_id_param BIGINT);
DROP FUNCTION IF EXISTS days_remaining(challenge_id_param BIGINT);
DROP FUNCTION IF EXISTS days_passed(challenge_id_param BIGINT);
DROP FUNCTION IF EXISTS time_progress_percentage(challenge_id_param BIGINT);
DROP VIEW IF EXISTS challenge_basic_analytics;
DROP FUNCTION IF EXISTS count_category_goals(category_id_param BIGINT);
DROP FUNCTION IF EXISTS count_category_habits(category_id_param BIGINT);
DROP FUNCTION IF EXISTS count_category_challenges(category_id_param BIGINT);
DROP FUNCTION IF EXISTS count_category_users(category_id_param BIGINT);
DROP FUNCTION IF EXISTS avg_category_goal_progress(category_id_param BIGINT);
DROP FUNCTION IF EXISTS avg_category_habit_consistency(category_id_param BIGINT);
DROP FUNCTION IF EXISTS calculate_category_activity_score(category_id_param BIGINT);
DROP FUNCTION IF EXISTS get_user_habits_consistency();
DROP VIEW IF EXISTS category_detailed_analytics;